### ISSUE TITLE
RFC 9267

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/dnsext#40]
Common Implementation Anti-Patterns Related to Domain Name System (DNS) Resource Record (RR) Processing:

**Comment by khibino** [comment]
Compression Pointer and Offset Validation

* "The destination buffer for the domain name ("name_buffer") is typically limited to 255 bytes as per [RFC1035] and can be allocated either in the stack or in the heap memory region."
* "The second issue is due to the absence of checks that ensure that a pointer will eventually arrive at a decompressed domain label."
* "a compression pointer set to "0xffff" will produce an offset of 16383 octets, which is most definitely pointing to a label length octet somewhere past the bounds of the original DNS packet"
* infinite-loop
* "various pointer loops that have other undesirable effects"

https://datatracker.ietf.org/doc/html/rfc9267#section-2

**Comment by kazu-yamamoto** [comment]
@khibino Would you change the item list above to the *check* list? (`- [ ] item`)

**Comment by kazu-yamamoto** [comment]
`getDomain'` has `ptrLimit`.
This means that only backward pointers are allowed resulting no loop.

**Comment by kazu-yamamoto** [comment]
Let's close.
